public class Quine1 {
    public static void main(String[] args) {
        char q = 34;
        String[] l = {
            "            ",
            "l[1]   *** Quine1.java ***",
            "public class Quine1 {",
            "    public static void main(String[] args) {",
            "        char q = 34;",
            "        String[] l = {",
            "        };",
            "        for( int i = 16; i <= 19; i++ )",
            "            System.out.println(l[i]);",
            "        for( int i = 0; i < l.length; i++ )",
            "            System.out.println( l[0] + q + l[i] + q + ',' );",
            "        for( int i = 20; i <= 28; i++ )",
            "            System.out.println( l[i] );",
            "    }",
            "}",
            "l[15]   *** Quine2.java ***",
            "public class Quine2 {",
            "    public static void main(String[] args) {",
            "        char q = 34;",
            "        String[] l = {",
            "        };",
            "        for( int i = 30; i <= 35; i++ )",
            "            System.out.println(l[i]);",
            "        for( int i = 0; i < l.length; i++ )",
            "            System.out.println( l[0] + q + l[i] + q + ',' );",
            "        for( int i = 36; i <= 45; i++ )",
            "            System.out.println( l[i] );",
            "    }",
            "}",
            "l[29]   *** Quine3.cs ***",
            "using System;",
            "namespace Quine3{",
            "    class Quine3{",
            "        static void Main(){",
            "        char q = Convert.ToChar(34);",
            "        String[] l = {",
            "        };",
            "        for( int i = 47; i <= 52; i++ )",
            "            Console.WriteLine( l[i] );",
            "        for( int i = 0; i < l.Length; i++ )",
            "            Console.WriteLine( l[0] + q + l[i] + q + ',' );",
            "        for( int i = 53; i <= 62; i++ )",
            "            Console.WriteLine(l[i]);",
            "        }",
            "    }",
            "}",
            "l[46]   *** Quine4.cs ***",
            "using System;",
            "namespace Quine4{",
            "    class Quine4{",
            "        static void Main(){",
            "        char q = Convert.ToChar(34);",
            "        String[] l = {",
            "        };",
            "        for( int i = 64; i <= 65; i++ )",
            "            Console.WriteLine( l[i] );",
            "        for( int i = 0; i < l.Length; i++ )",
            "            Console.WriteLine( l[0] + q + l[i] + q + ',' );",
            "        for( int i = 66; i <= 75; i++ )",
            "            Console.WriteLine(l[i]);",
            "        }",
            "    }",
            "}",
            "l[63]   *** Quine5.rb ***",
            "q = 34.chr",
            "s = [",
            "]",
            "77.upto(78) do |i|",
            "    puts (s[i])",
            "end",
            "0.upto(s.size-1) do |i|",
            "    puts ( s[0] +q + s[i] + q + ',' )",
            "end",
            "79.upto(88) do |i|",
            "    puts (s[i])",
            "end",
            "l[76]   *** Quine6.rb ***",
            "q = 34.chr",
            "s = [",
            "]",
            "2.upto(5) do |i|",
            "    puts (s[i])",
            "end",
            "0.upto(s.size-1) do |i|",
            "    puts ( s[0] +q + s[i] + q + ',' )",
            "end",
            "6.upto(14) do |i|",
            "    puts (s[i])",
            "end",
        };
        for( int i = 16; i <= 19; i++ )
            System.out.println(l[i]);
        for( int i = 0; i < l.length; i++ )
            System.out.println( l[0] + q + l[i] + q + ',' );
        for( int i = 20; i <= 28; i++ )
            System.out.println( l[i] );
    }
}
